### ISSUE TITLE
[meta/deploy] unravel removing subdomains and loading without a config file

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#134]
At the moment it's pretty messy, for example a `country` param is already required for a request to the API to find out what `instance` configs are available
- [ ] can the `country` param be empty?
- [ ] should configs only be available to authorised users (yes, probably)
- [ ] and/or should a user say which configs they're interested in (e.g incl public ones)
- [ ] only show the configs a user is allowed to see
- [ ] simplify the loading process
- [ ] simplify the storage of instance configs
- [ ] what happens if you want to switch config when you're offline? (should not be able to?)
- [ ] we're relying on subdomains for GA to split between different instances - could swap to checking in path

List out what we're relying on subdomains for:
- keeping instance-specific files cached with SW
- IDB stores
- Vuex localstorage
- GA

Benefits from dropping subdomains:
- [ ] simpler remote e2e testing
- [ ] easier to deploy to more different services

Links to: https://github.com/disarm-platform/user-requests-and-feedback/issues/12
