### ISSUE TITLE
[aggregations] filter more efficiently

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#153]
We're iterating every response for every filter. How can we reduce this?

- [ ] Smarter indexing: [Segment Trees](https://hackernoon.com/practical-data-structures-for-frontend-applications-when-to-use-segment-trees-9c7cdb7c2819)?
- [x] Combine multiple predicate functions into a single function - i.e. multiple filter elements into one filter. We'd then only iterate the array of responses once. (done in #154)
- [ ] Freezing or using immutable arrays (it's immutable data anyway)
- [x] `for` instead of `filter`? [really](https://jsbench.me/tljgq5rd8t/1) surely we're getting some benefits from some transpilation step? But note that this isn't based on any measurements - the loop might be a tiny part of the overall time cost. (done in #154)
