### ISSUE TITLE
[meta] Create Diagram of config

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#283]
@onlyjsmith commented on [Mon Apr 30 2018](https://github.com/locational/_tickets/issues/22)

- [ ] add image to `douma-api` repo for reference
- [ ] `users` separate to instance authorisation
- [x] version geodata and related config files
