### ISSUE TITLE
[meta] Create UML Diagram of db (and all data, config, etc)

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#284]
@onlyjsmith commented on [Mon Apr 30 2018](https://github.com/locational/_tickets/issues/22)

- [ ] add image to `douma-api` repo for reference
- [ ] `users` separate to instance authorisation
- [ ] version geodata and related config files
