### ISSUE TITLE
[meta] redeploy production app

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#42]
Need to think this through asap

- [ ] check analytics - anyone using it?

#### Essential
- [ ] add ssh key to github
- [ ] `rm douma-app`
- [ ] clone repo
- [ ] `npm run build`

#### Bonus
- [ ] edit caddyfile
